name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.30.3'

      - name: Build project
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Upload debug APKs
        uses: actions/upload-artifact@v4
        with:
          name: debug-apks
          path: ./app/build/outputs/apk/debug/*.apk

      - name: Upload release APKs
        uses: actions/upload-artifact@v4
        with:
          name: release-apks
          path: ./app/build/outputs/apk/release/*.apk
